### ISSUE TITLE
[Functions] Fix logic and behavior of generate_strings() and frequency_anchors()

### ISSUE THREAD

**Issue by gsvidaurre** [gsvidaurre/paRsynth#32]
Currently frequency_anchors() converts the entire Parsons code sequence to frequency values rather than converting one section at a time. This logic does not line up with how information is originally encoded in the character strings by generate_strings(). We need to make sure that the logic of information encoding is the same for both steps of information encoding (character strings and synthetic acoustic signals), especially given our plans for downstream analyses to recover information.

Right now each vector of frequency anchors contains more stochasticity of information encoding than we expect, because the trajectory of later frequency values depends on earlier frequency values, and therefore the global tail becomes very different across calls (when it should be exactly the same). This problem is especially true for long character strings (e.g. 150 characters), and may be leading to downstream problems with negative frequency values assigned to frequency anchors, as well as negative values appearing in spectrographic cross-correlation matrices.

We can discuss a solution in more detail, but right now I'm thinking it will be easiest to save each of the sections of each character string (global head, group info_head, global_info_tail, individual info, and global tail) in separate columns in generate_strings(), as well as the full character string, which should also simplify unit testing. Then frequency_anchors() should create vectors of frequency anchors for each character string separately before concatenating these vectors together to create a single time series per vocalization.

**Comment by raneemsamman** [comment]
I just committed the changes I have been working on for this issue. I am curious to hear what you think when you have a chance to look at them. I will create a pull request for that issue after you give it the thumps up.

**Comment by gsvidaurre** [comment]
Thanks @raneemsamman! I just checked out your most recent commit and this will be ready for a pull request after some minor changes:

- [ ] Add an argument to frequency_anchors() to facilitate 2 options for how the frequency anchors are generated across sections. The argument can be called `section_transition`, and the possible values can be "starting_frequency" or "continuous_trajectory". The option "starting_frequency" can be the option that you currently have, in which the starting frequency specified by the user is used as the starting frequency per section. The option "continuous_trajectory" should instead use the last frequency value of the previous section as the starting frequency of the section to be generated
- [ ] Move the helper function outside of the main function (it can be placed just after the code for frequency_anchors() )
- [ ] Clean up comments and older code inside of the function. You can remove lines of code that we are not currently using (commented out) and you can also update the comments to remove info about fixed (since we can see this info in the commit history) and to focus on what each line of code does
- [ ] You can remove your comments about the seq_len() option to catch cases in which an input data frame has no rows. But definitely add this general idea to the issue #12 about error handling. For each function, we should write an error handling statement that checks whether the input data exists and is not empty. This explicit check will be more useful for providing feedback to users

Let me know if anything above is confusing, happy to expand more!

**Comment by raneemsamman** [comment]
Just finished updating the code and committed it. Did I get what you meant by the section_transition right? Happy to edit it/add anything/change anything if I misunderstood anything!!

**Comment by gsvidaurre** [comment]
Just checked out the updated code @raneemsamman! This updated logic makes sense to me, including the updates for the two modes of creating the frequency anchors and the new argument `section_transition`. 

For the code that implements the two modes of transitions, can you set up the code inside of each conditional to loop over the different sections and set the previous_frequency? This should reduce the amount of code needed here
