### ISSUE TITLE
[Functions & Unit Tests] Check documentation, remove older lines of code, Check for typos and grammatical issues, Check that internal packages are loaded

### ISSUE THREAD

**Issue by gsvidaurre** [gsvidaurre/paRsynth#45]
We don't need to include older code that we're no longer using in each function. To fix this, check each of the functions and remove code that is commented out. We also need to check all of the documentation per function for the following: Are all statements clear? Are there any typos or grammatical errors?

Check all of the documentation across unit tests for the following: Are all statements clear / not missing words? Are there any typos or grammatical errors?
This issue was merged with issue #49 

Across unit tests, make sure that the lines to load packages inside of each unit test are uncommented.
This issue was merged with issue #48

**Comment by juarezgr** [comment]
Finished ready to be pulled

**Comment by raneemsamman** [comment]
we need to add new lines of documentation for the updated parameters/function arguments once we pull the changes from PAR-32.
